export const projects = [
  {
    id: 4,
    title: "Mail chat",
    photoURL: "mail-chat.png",
    about: "A fast chat app using redis server and push sockets.",
    link: "https://mail-chat-rose.vercel.app/",
    github: "https://github.com/samualhalder/chat-app-nextjs",
    tech: ["next", "ts", "redis", "tailwind"],
  },
  {
    id: 3,
    title: "Feedback Hub",
    photoURL: "feedback-hub.png",
    about: "Take feedback from your user and share them as a testimonials.",
    link: "https://feedback-hub-kung.onrender.com/",
    github: "https://github.com/samualhalder/mern-feedback-app",
    tech: ["react", "ts", "node", "express", "tailwind", "mongo", "docker"],
  },
  {
    id: 2,
    title: "TechNuze",
    photoURL: "techNuze-project.png",
    about: "A a fully functional news site for latest news related tech world.",
    link: "https://technuze.onrender.com/",
    github: "https://github.com/samualhalder/TechNuze",
    tech: ["react", "ts", "node", "express", "tailwind", "mongo"],
  },
  {
    id: 1,
    title: "Hello mall",
    photoURL: "hello-mall.png",
    about: "A a fully functional e-commerce site with stripe payment gateway.",
    link: "https://mern-ecommerce-delta-one.vercel.app/",
    github: "https://github.com/samualhalder",
    tech: ["react", "js", "node", "express", "tailwind", "mongo"],
  },
];
